/**
 * ==============================================================================
 * AURA AI — DATABASE MODEL: models/Chat.js
 * ==============================================================================
 * 
 * TUTORIAL EXPLANATION FOR BEGINNERS:
 * ------------------------------------------------------------------------------
 * What is MongoDB?
 * MongoDB is a NoSQL, document-oriented database. Instead of rows and tables like
 * SQL databases, MongoDB stores records as flexible JSON-like documents.
 * 
 * What is Mongoose?
 * Mongoose is an "Object Data Modeling" (ODM) library for Node.js. It acts as a 
 * bridge between your JavaScript backend code and your MongoDB database. Mongoose
 * helps us define the exact structure (Schema) of our documents, validate types,
 * and easily save/retrieve data with simple JavaScript methods like:
 *   - await Chat.create({ ... })
 *   - await Chat.find().sort({ timestamp: -1 })
 * ==============================================================================
 */

const mongoose = require('mongoose');

/**
 * STEP 1: DEFINE THE SCHEMA
 * ------------------------------------------------------------------------------
 * A Schema is the blueprint that describes what data fields each document must
 * or can have, their data types (String, Date, Number, etc.), and validation rules.
 */
const ChatSchema = new mongoose.Schema(
  {
    // The prompt or question typed by the user in the frontend input box
    userPrompt: {
      type: String,
      required: [true, 'User prompt is required to save a chat turn.'],
      trim: true
    },

    // The conversational response generated by Google Gemini AI
    botResponse: {
      type: String,
      required: [true, 'Bot response is required to save a chat turn.'],
      trim: true
    },

    // Timestamp representing exactly when this exchange occurred
    timestamp: {
      type: Date,
      default: Date.now // Automatically sets the current date/time if not provided
    },

    // Optional metadata object for future scaling (e.g., model used, token count, IP)
    metadata: {
      model: {
        type: String,
        default: 'gemini-1.5-flash'
      },
      clientIp: {
        type: String,
        default: 'unknown'
      }
    }
  },
  {
    // Optional schema options: timestamps: true automatically adds createdAt & updatedAt
    timestamps: true
  }
);

/**
 * STEP 2: CREATE AND EXPORT THE MONGOOSE MODEL
 * ------------------------------------------------------------------------------
 * The model compiles the Schema into a usable JavaScript class.
 * 'Chat' will correspond to the 'chats' collection inside your MongoDB database.
 * 
 * In server.js, we will import this model to save conversations:
 *   const Chat = require('./models/Chat');
 *   await Chat.create({ userPrompt, botResponse });
 */
const Chat = mongoose.model('Chat', ChatSchema);

module.exports = Chat;
